_wandb:
    value:
        cli_version: 0.22.2
        e:
            20bugt8sify5qdj3yklc23h1xutrkqki:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "75125227520"
                        used: "25613832192"
                email: p24cs0005@iitj.ac.in
                executable: /csehome/p24cs0005/miniconda3/envs/lidar4d/bin/python
                gpu: NVIDIA A30
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-b0bff278-bb55-d6e3-2095-79f7d73ae915
                host: cn01
                memory:
                    total: "269827448832"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /csehome/p24cs0005/ppmf/preet/train.py
                python: CPython 3.9.23
                root: /csehome/p24cs0005/ppmf/preet
                slurm:
                    cluster_name: csedpu
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    cpus_per_task: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: root
                    job_cpus_per_node: "1"
                    job_end_time: "1762413099"
                    job_gid: "2005"
                    job_gpus: "1"
                    job_id: "18219"
                    job_name: temporal
                    job_nodelist: cn01
                    job_num_nodes: "1"
                    job_partition: phd
                    job_qos: normal
                    job_start_time: "1761916299"
                    job_uid: "2345"
                    job_user: p24cs0005
                    jobid: "18219"
                    localid: "0"
                    mem_per_cpu: "8192"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cn01
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /csehome/p24cs0005/ppmf/preet
                    submit_host: login.cse.iitj.ac.in
                    task_pid: "1315592"
                    tasks_per_node: "1"
                    topology_addr: cn01
                    topology_addr_pattern: node
                    tres_per_task: cpu:1
                startedAt: "2025-10-31T13:12:19.188872Z"
                writerId: 20bugt8sify5qdj3yklc23h1xutrkqki
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 83
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 83
            "3":
                - 13
                - 16
            "4": 3.9.23
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
DATA_CONFIG:
    value:
        COMPUTE_MEAN_AND_STD: false
        DATALOADER:
            NUM_WORKER: 4
            SHUFFLE: true
        DATASET_NAME: KITTIOdometry
        FOV_DOWN: -25
        FOV_UP: 3
        GENERATE_FILES: false
        HEIGHT: 64
        MAX_RANGE: 85
        MEAN:
            - 10.839
            - 0.005
            - 0.494
            - -1.13
            - 0
        MIN_RANGE: 1
        PROCESSED_PATH: /scratch/p24cs0005/kitti/processed_data
        RAW_PATH: /scratch/p24cs0005/kitti/dataset/sequences
        SPLIT:
            TEST:
                - 8
                - 9
                - 10
            TRAIN:
                - 0
                - 1
                - 2
                - 3
                - 4
                - 5
            VAL:
                - 6
                - 7
        STD:
            - 9.314
            - 11.521
            - 8.262
            - 0.828
            - 1
        WIDTH: 2048
EXPERIMENT:
    value:
        ID: kitti_exp
        SEED: 43
MODEL:
    value:
        3D_CHANNELS:
            - 256
        CHANNELS:
            - 16
            - 32
            - 64
            - 128
        CIRCULAR_PADDING: true
        MASK_THRESHOLD: 0.5
        N_CHANNELS_PER_GROUP: 16
        N_FUTURE_STEPS: 5
        N_PAST_STEPS: 5
        NORM: batch
        SKIP_IF_3D_CHANNEL_SIZE: null
        SKIP_IF_CHANNEL_SIZE:
            - 32
            - 64
        TEMPORAL_KERNEL_SIZE:
            - 2
        USE:
            INTENSITY: false
            XYZ: false
TEST:
    value:
        N_BATCHES_TO_SAVE: -1
        N_DOWNSAMPLED_POINTS_CD: -1
        SAVE_POINT_CLOUDS: false
        SELECTED_SEQUENCE_AND_FRAME:
            "8":
                - 92
        USE_GROUND_MASK: false
        USE_OBJECT_MASK: false
TRAIN:
    value:
        BATCH_ACC: 1
        BATCH_SIZE: 4
        LOG_EVERY_N_STEPS: 10
        LOSS_WEIGHT_CHAMFER_DISTANCE: 0
        LOSS_WEIGHT_MASK: 1
        LOSS_WEIGHT_RANGE_VIEW: 1
        LR: 0.0003
        LR_DECAY: 0.99
        LR_EPOCH: 1
        MAX_EPOCH: 100
        N_GPUS: 1
VALIDATION:
    value:
        SELECTED_SEQUENCE_AND_FRAME:
            "6":
                - 4
                - 10
